[hacenada]
name = "Deploy Jobbergate"
description = "Deploy Jobbergate to a stage and region"

[[step]]
# label =  # (autonumbered, "<type>-<n>")
# type = "message"  # default type
message = """
    Let's get started deploying jobbergate

    Before we get started, please gather the following:

    - xxx
    - yyy
    """
stop = false

[[step]]
# label =  # (auto)
label = "description"
type = "description"
message = """
    Please enter a description for this operation, such as "Deploying v0.2 to eu-north-1 staging"
    """
stop = false

[[step]]
# label =  # (auto)
type = "confirm"
message = "Have you gathered all that?"
repeat-if = false

# first stop occurs naturally here
