#!/usr/bin/env bash

# create a github release with the gh tool

set -euo pipefail
IFS=$'\n\t'

ver="$1"
token="$2"
shift; shift
artifacts=( "$@" )

gh auth login --with-token <<< "$token"
gh release create -t "Release $ver" -n "## Release $ver" "$ver" "${artifacts[@]}"
