name: hacenada

base: core20 # python 3.8

adopt-info: hacenada
summary: Hacenada is for writing do-nothing scripts in .toml format
grade: stable
confinement: classic

apps:
  hacenada:
    environment:
      PATH: $SNAP/bin/:$PATH
      PYTHONPATH: $SNAP/lib/python3.8/site-packages/
    command: bin/hacenada

parts:
  hacenada:
    plugin: python
    parse-info: ['setup.py']
    python-packages: [wheel]
    source: .
